### ISSUE TITLE
Is there any CRD or yaml files to deploy the operator itself

### ISSUE THREAD

**Issue by sjmittal** [sky-big/pulsar-operator#11]
Hi,
Right now going through the code it seems we need to run `make install` to deploy the operator.
Is there a way to deploy the `CustomResourceDefinition` used by the operator and the `Deployment` of the operator itself via yaml files which are applied to k8s directly using `kubectl apply -f`.

This way we can use it in any k8s cluster without having to clone the repo and making the installer available locally.

**Comment by sky-big** [comment]
https://github.com/apache/pulsar/tree/master/deployment/kubernetes/helm/pulsar

**Comment by sky-big** [comment]
Please refer to here

**Comment by sjmittal** [comment]
Actually I was looking for a simple yaml file to deploy this operator using command like:
`kubectl apply -f k8s/vault-operator.yaml`
I have created a simple one which I am attaching
https://gist.github.com/sjmittal/35197d02e2d5138813982f138be5a9b6

This deploys the operators pod in the desired namespace. It picks the image from `skybig/pulsar-operator:latest`.

I see the pod status as running but when I view the logs I get this repeated error message like:
`E0608 05:50:02.753885       1 reflector.go:134] pkg/mod/k8s.io/client-go@v0.0.0-20190228174230-b40b2a5939e4/tools/cache/reflector.go:95: Failed to list *unstructured.Unstructured: the server could not find the requested resource`

Please let me know if this message is to be ignored or needs to be fixed or is fixed.

**Comment by sky-big** [comment]
I have packed the Chart ： https://github.com/sky-big/pulsar-operator/tree/master/chart

**Comment by sky-big** [comment]
You created YAML with an error ： https://gist.github.com/sjmittal/35197d02e2d5138813982f138be5a9b6

**Comment by sky-big** [comment]
If you don't want to use helm，you can use `kubectl apply -f ` like this:

1. kubectl apply -f chart/templates/crds/pulsar_operator_crd.yaml

2. kubectl apply -f chart/templates/pulsar_operator_rbac.yaml

3. kubectl apply -f chart/templates/pulsar_operator_deployment.yaml

**Comment by sjmittal** [comment]
So the combined yaml I have created actually contains the three yamls mentioned above.
Can you please let me know what is the error in the YAML I have created.
This YAML gets applied correctly by `k8s` and operator is deployed.

So what may be causing the error in the operator logs?

**Comment by sky-big** [comment]
Your YAML information is incomplete, please check it again, it is inconsistent with THE YAML in the project

**Comment by sjmittal** [comment]
I have check the yamls you have suggested.
The YAML information I have using is pretty standard and minimal and I am able to deploy other `go` based operators built using `OperatorSDK`.

One thing here is that the CRD is `cluster` scoped. There seems some issues logged related to this issue on `operator-sdk`.
eg: https://github.com/operator-framework/operator-sdk/issues/1858
Is it something like this operator is using some older version of `OperatorSDK`?

I am trying to understand what part of my YAML are inconsistent with project YAMLs,

Could you please help me in understanding these:
1. 
```
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "pulsar-operator"
```
Since I am deploying the operator in `namespace: operators-ec-core` then do I need the `WATCH_NAMESPACE` property set to `metadata.namespace` because the the pulsar cluster will be deployed in default namespace? 
What if I need the operator to watch all namespaces? Then what value should I provide here.
Also what is the purpose of `POD_NAME`?

2. The only other issue then can be with `pulsar_operator_rbac.yaml`, I will check that.
Is there any obvious inconsistency you see with my provided YAML?

**Comment by sky-big** [comment]
```
 env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
```
I forgot to delete it.

The main differences are in pulsar_operator_rbac.yaml and pulsar_operator_crds.yaml

**Comment by sky-big** [comment]
I need permission to operate PulsarCluster, a CRD resource

**Comment by sky-big** [comment]
Please use chart to install it directly. I have passed the test

**Comment by sjmittal** [comment]
Is there a slack or community channel I can join?

I cannot use helm because right now this operator is getting installed from some other framework.
Looks like I cannot remove `WATCH_NAMESPACE` so I have set this as:
```
            - name: WATCH_NAMESPACE
              value: "*"
```
Also in my YAML I have added the CRD and also I have a standard `rbac` with `ServiceAccount` and  `ClusterRoleBinding` with permission as `name: cluster-admin`.

**Comment by sky-big** [comment]
`cluster-admin`   I am not sure that I have operation permissions for PulsarCluster.      `WATCH_NAMESPACE`  This parameter is not set and is not used in the operator.

**Comment by sjmittal** [comment]
I am now using `chart/templates/pulsar_operator_rbac.yaml` and I get same error as before.

So issue is not with `rbac`.

Note that the `cluster-admin` ClusterRole exists by default in your Kubernetes cluster, and allows superuser operations in all of the cluster resources. So if I assign this cluster role instead, it should have all the permission.

Note that so far I have not created any instance of `pulsarclusters`. I have just deployed the operator. These are the logs which operator generates.
Hope this helps.

**Comment by sjmittal** [comment]
Please check the `operator-sdk` issue https://github.com/operator-framework/operator-sdk/issues/1858.
The issue is happening because CRD is cluster scoped whereas operator is namespace scoped.
This issue was fixed in https://github.com/redhat-developer/build/pull/73.

Perhaps updating to latest sdk version will help with this issue.

**Comment by sky-big** [comment]
ok，I'll keep an eye on that.

**Comment by sjmittal** [comment]
Also check this:
https://github.com/operator-framework/operator-sdk/pull/2601/

Can we move to a later version of sdk and rebuild this operator's image to see if these errors are fixed?

**Comment by sky-big** [comment]
If you have time, you can bring up MR to fix it

**Comment by sjmittal** [comment]
Unfortunately I am not much knowledgeable about `go`. I am using this operator from a `java` based framework.
For now I am ignoring the error 
` Failed to list *unstructured.Unstructured: the server could not find the requested resource`

However now when I do try to add a CR I get this error:
https://pastebin.com/0YLYFHav

Looks like error is around:
` "error": "an empty namespace may not be set during creation",`
However I have not defined any namespace and my operator and the CR are all created in default namespace.

Here is the definition of my CR:
https://pastebin.com/DifED5tV

**Comment by sjmittal** [comment]
Also please check comment
https://github.com/operator-framework/operator-sdk/issues/1858#issuecomment-530952613

Looks like "requested resources not found" issue happened with more recent versions of `k8s`
So please check with latest version of `k8s`.

Maybe "empty namespace" issue is also related to recent versions of `k8s`.

**Comment by sky-big** [comment]
Is it still a problem for you to deploy Pulsar Operators completely by using Yaml in the Chart directory?
Can you try it?
@sjmittal

**Comment by sky-big** [comment]
I'll test and fix it later with the Yaml you wrote.

**Comment by sjmittal** [comment]
@sky-big  I did finally deploy the operator completely using YAML as per charts directory.
Note that operator does deploy correctly except for those pesky logs of 
`Failed to list *unstructured.Unstructured: the server could not find the requested resource`

But when I try to deploy the pulsar cluster CR (pastebins attached above) I get into the error which is something like:
`"error": "an empty namespace may not be set during creation",`

If possible, we can try to upgrade this operator to latest operator sdk version. This will anyway be helpful even if this issue is not caused due to that.

Please see if we can have the discussion on slack channel created as a response of this operator.
https://app.slack.com/client/T5Z3B324U/CTESFK98C

I would prefer to use the operator against helm charts to deploy pulsar cluster.

**Comment by sky-big** [comment]
https://app.slack.com/client/TSK90ANQK/CSYV5L9FG, I used slack before.  @sjmittal

**Comment by sky-big** [comment]
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a17149e1a189050796ced469dbd78d380f2ed5ef", GitTreeState:"clean", BuildDate:"2020-04-16T11:44:51Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2019-12-11T12:32:32Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
I can deploy successfully in this version of Kubernetes, and the operator is deployed in default Namespace

**Comment by sjmittal** [comment]
I am not able to join that channel.
I was able to join this channel for pulsar operator: https://app.slack.com/client/T5Z3B324U/CTESFK98C 
Would be nice to see you around.
I think my Kubernetes version is 1.18, I will again check deploying the operator.
I think difference at my end is mostly that my pulsar operator is in a named namespace.

**Comment by sky-big** [comment]
Pulsar slack channel at https://apache-pulsar.slack.com/

You can self-register at https://apache-pulsar.herokuapp.com/

Use this.

**Comment by sjmittal** [comment]
Yes I am in that channel. I had left a message for you @sky-big

**Comment by sky-big** [comment]
> Yes I am in that channel. I had left a message for you @sky-big

OK

**Comment by sky-big** [comment]
#12  Fix it.   @sjmittal

**Comment by sjmittal** [comment]
So with the changes I am able to deploy operator (for now I have set the scope as `Namespaced` for my CRDs), without any pesky log messages.
However when I deploy the CR I get this error:
```
    "logger": "controller_pulsarcluster",
    "msg": "Reconciling PulsarCluster Zookeeper Error",
    "Request.Namespace": "myco-test",
    "Request.Name": "datastream",
    "error": "poddisruptionbudgets.policy \"datastream-zookeeper-poddisruptionbudget\" already exists",
```

I had stripped down your CRD and right now my CRD is as followed:
https://gist.github.com/sjmittal/6dbaeeb9edc9d08a95ef666ecc60f04c

Also my CR is very basic:
```
apiVersion: pulsar.apache.org/v1alpha1
kind: PulsarCluster
metadata:
  name: ""
spec:
  bookie:
    storageClassName: fast
    journalStorageCapacity: 1
    ledgersStorageCapacity: 1
    size: 1
  broker:
    size: 1
  proxy:
    size: 1
  zookeeper:
    size: 1
  manager:
    enable: true
```
Any idea on what I should be looking at.

**Comment by sky-big** [comment]
`datastream-zookeeper-poddisruptionbudget`  Resources are already in that Namespace, so you need to clean up Namespace or get a new Namespace.
