### ISSUE TITLE
Pulsar operator is not parsing docker repository correctly

### ISSUE THREAD

**Issue by sjmittal** [sky-big/pulsar-operator#17]
Hi,
I have  a following CR spec:
```
Spec:
  Auto Recovery:
    Image:
    Pod:
      Components:
    Size:  3
  Bookie:
    Image:
      Pull Policy:             Always
      Repository:              10.108.43.202:8082/path/to/pulsar-all
      Tag:                     latest
    Journal Storage Capacity:  1
    Ledgers Storage Capacity:  1
    Pod:
      Components:
    Size:                1
    Storage Class Name:  standard
  Broker:
    Image:
      Pull Policy:  Always
      Repository:   10.108.43.202:8082/path/to/pulsar-all
      Tag:          latest
    Pod:
      Components:
    Size:  1
  Manager:
    Enable:  true
    Image:
      Pull Policy:  Always
      Repository:   10.108.43.202:8082/path/to/pulsar-manager
      Tag:          latest
    User Name:      pulsar
    User Password:  pulsar
  Monitor:
    Grafana:
    Ingress:
    Prometheus:
  Proxy:
    Image:
      Pull Policy:  Always
      Repository:   10.108.43.202:8082/path/to/pulsar
      Tag:          latest
    Pod:
      Components:
    Size:  1
  Zookeeper:
    Image:
      Pull Policy:  Always
      Repository:   10.108.43.202:8082/path/to/pulsar-all
      Tag:          latest
    Pod:
      Components:
    Size:  1
```
Note that docker registry is running at private IP `10.108.43.202:8082`
However when starting the bookie pod I see the following errors:

```
  Warning  InspectFailed  5m32s (x13 over 7m46s)  kubelet, minikube  Failed to apply default image tag ":": couldn't parse image reference ":": invalid reference format
  Warning  Failed         2m44s (x26 over 7m46s)  kubelet, minikube  Error: InvalidImageName
```

I think if registry is running at some port, it is not able to parse the repo correctly.
Also note that proxy, zookeeper and manager are all running correctly, so issue seems only with bookie.

**Comment by sky-big** [comment]
Can you take a look at bookie's YAML details for the Pod and see if the docker image address in the Pod is correct？

**Comment by sjmittal** [comment]
Unfortunately I don't have this detail now, I decided to run docker registry at port 80 and referenced the image without port and all worked fine. So issue seems to be with port only and that too only for bookie.
I doubt docker image address on pod would have been correct, I think it had `:` in place of tag.
What I suspect is that it maybe parsing the repository to check for `:` and if it finds a value for it, it assumes that's the image tag.
Since in this case supposedly parsed tag is a port number and not a valid tag, we get that error.

**Comment by rfinner** [comment]
I am also having a problem with the bookie image name: 
k logs jericho-pulsarcluster-bookie-autorecovery-deployment-746772srbv
Error from server (BadRequest): container "replication-worker" in pod "jericho-pulsarcluster-bookie-autorecovery-deployment-746772srbv" is waiting to start: InvalidImageName
I am running on EKS with :
apiVersion: pulsar.apache.org/v1alpha1
kind: PulsarCluster
metadata:
  name: jericho-pulsarcluster
spec:
  zookeeper:
    size: 3
  autoRecovery:
    size: 3
  bookie:
    size: 3
    storageClassName: "gp2"
    journalStorageCapacity: 10
    ledgersStorageCapacity: 10
  broker:
    size: 3
  proxy:
    size: 3
  monitor:
    enable: true                
    prometheusPort: 30002       
    grafanaPort: 30003          
    ingress:                
      enable: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
  manager:
    enable: true
    annotations:
      kubernetes.io/ingress.class: "nginx"

**Comment by sky-big** [comment]
Could you please provide the Yaml information of this Pod 'Jericho - Pulsarclub-Bookie - Autorecovery-Deploy-746772SRbv'?
For example 'Kubectl get POD Jericho - Pulsarclub-Bookie - Autorecovery-Deploy-746772srBV-O Yaml' post the results. @rfinner

**Comment by rfinner** [comment]
k logs example-pulsarcluster-bookie-autorecovery-deployment-c79b4rsv8c
Error from server (BadRequest): container "replication-worker" in pod "example-pulsarcluster-bookie-autorecovery-deployment-c79b4rsv8c" is waiting to start: InvalidImageName

**Comment by rfinner** [comment]
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: eks.privileged
  creationTimestamp: "2020-09-11T16:41:04Z"
  generateName: example-pulsarcluster-bookie-autorecovery-deployment-c79b476d9-
  labels:
    app: pulsar
    cluster: example-pulsarcluster
    component: autoRecovery
    pod-template-hash: c79b476d9
  name: example-pulsarcluster-bookie-autorecovery-deployment-c79b4rsv8c
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: example-pulsarcluster-bookie-autorecovery-deployment-c79b476d9
    uid: 6418301e-2f05-4ec5-b909-8a71cb19e644
  resourceVersion: "3905968"
  selfLink: /api/v1/namespaces/default/pods/example-pulsarcluster-bookie-autorecovery-deployment-c79b4rsv8c
  uid: 191c39d3-3594-4600-90ad-2f8ba8c2e9ac
spec:
  containers:
  - args:
    - bin/apply-config-from-env.py conf/bookkeeper.conf && bin/bookkeeper autorecovery
    command:
    - sh
    - -c
    env:
    - name: BOOKIE_MEM
      value: '" -Xmx256m "'
    - name: PULSAR_GC
      value: '"  "'
    envFrom:
    - configMapRef:
        name: example-pulsarcluster-bookie-configmap
    image: ':'
    imagePullPolicy: IfNotPresent
    name: replication-worker
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-9qgpn
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: ip-192-168-57-243.us-west-2.compute.internal
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-9qgpn
    secret:
      defaultMode: 420
      secretName: default-token-9qgpn
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-09-11T16:41:04Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-09-11T16:41:04Z"
    message: 'containers with unready status: [replication-worker]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-09-11T16:41:04Z"
    message: 'containers with unready status: [replication-worker]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-09-11T16:41:04Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: ':'
    imageID: ""
    lastState: {}
    name: replication-worker
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: 'Failed to apply default image tag ":": couldn''t parse image reference
          ":": invalid reference format'
        reason: InvalidImageName
  hostIP: 192.168.57.243
  phase: Pending
  podIP: 192.168.38.109
  podIPs:
  - ip: 192.168.38.109
  qosClass: BestEffort
  startTime: "2020-09-11T16:41:04Z"

**Comment by rfinner** [comment]
image: ':'
    imagePullPolicy: IfNotPresent

**Comment by rfinner** [comment]
i also have same problem with the most simple of configs: apiVersion: pulsar.apache.org/v1alpha1
kind: PulsarCluster
metadata:
  name: example-pulsarcluster
spec:
  zookeeper:
    size: 3
  autoRecovery:
    size: 3
  bookie:
    size: 3
  broker:
    size: 3
  proxy:
    size: 3

**Comment by rfinner** [comment]
The 2.5.0 image seems to work fine and so maybe this has something to do with the latest version?

This deployment worked for me:

apiVersion: pulsar.apache.org/v1alpha1
kind: PulsarCluster
metadata:
  name: example-pulsarcluster
spec:
  autoRecovery:
    size: 1
    image:
      repository: apachepulsar/pulsar-all
      tag: 2.5.0
      pullPolicy: Always
  bookie:
    size: 1
    image:
      repository: apachepulsar/pulsar-all
      tag: 2.5.0
      pullPolicy: Always
  broker:
    size: 1
    image:
      repository: apachepulsar/pulsar-all
      tag: 2.5.0
      pullPolicy: Always
  proxy:
    size: 1
    image:
      repository: apachepulsar/pulsar-all
      tag: 2.5.0
      pullPolicy: Always
  zookeeper:
    size: 1
    image:
      repository: apachepulsar/pulsar-all
      tag: 2.5.0
      pullPolicy: Always
  monitor:
    enable: true
    prometheus:
      nodePort: 30006
    grafana:
      nodePort: 30007

**Comment by rfinner** [comment]
After more testing I discovered that docker pull apachepulsar/pulsar-all:2.6.0 and 2.6.1 are not working with this operator but 2.5.2 seems to be working.
