### ISSUE TITLE
Opinionated Bookkeeper Defaults Decrease Throughput Performance on Large Cluster

### ISSUE THREAD

**Issue by michaeljmarshall** [sky-big/pulsar-operator#18]
The configuration for `dbStorage_writeCacheMaxSizeMb` and `dbStorage_readAheadCacheMaxSizeMb` each default to 32.

https://github.com/sky-big/pulsar-operator/blob/2e5d026abdcd4781c41e03f03d7253ccba9eb46c/pkg/pulsar/components/bookie/constant.go#L6-L8

This configuration is very opinionated considering pulsar (and bookkeeper) defaults these values to 25% of the available memory.

https://github.com/apache/bookkeeper/blob/3a8f4b4d3e762ac24a0563eeaffd068efaab2b81/conf/bk_server.conf#L660-L663

I recently discovered that my pulsar cluster was under-performing on throughput because these caches were undersized. Given that there seem to be appropriate defaults in pulsar itself, I think it would be valuable to remove these restrictive defaults. Obviously, I can just override the default and move on, but it took me a while to figure out why my pulsar cluster was under-performing, so I thought I'd share here.

Thanks!

**Comment by sky-big** [comment]
Do you need to be flexible with CRD configuration?

**Comment by michaeljmarshall** [comment]
I'm not sure I understand your question. My point is that I don't see any value added by overriding the default behavior provided by pulsar, which is to allocate 25% of direct memory to each of these caches, as shown [here](https://github.com/apache/pulsar/blob/master/site2/website/versioned_docs/version-2.6.2/reference-configuration.md). The dynamic defaults make for appropriate sized caches regardless of the size of ones deployment.

To be fair, I was looking at how the pulsar helm chart sets these [values](https://github.com/apache/pulsar-helm-chart/blob/eb63a19964d7a4dab84278ceede0c61b996e5ebc/charts/pulsar/values.yaml#L484-L485), and it appears that the helm chart uses 32 for each config, just like this project.

**Comment by sky-big** [comment]
> I'm not sure I understand your question. My point is that I don't see any value added by overriding the default behavior provided by pulsar, which is to allocate 25% of direct memory to each of these caches, as shown [here](https://github.com/apache/pulsar/blob/master/site2/website/versioned_docs/version-2.6.2/reference-configuration.md). The dynamic defaults make for appropriate sized caches regardless of the size of ones deployment.
> 
> To be fair, I was looking at how the pulsar helm chart sets these [values](https://github.com/apache/pulsar-helm-chart/blob/eb63a19964d7a4dab84278ceede0c61b996e5ebc/charts/pulsar/values.yaml#L484-L485), and it appears that the helm chart uses 32 for each config, just like this project.

yes, it is.

**Comment by sky-big** [comment]
```
apiVersion: pulsar.apache.org/v1alpha1
kind: PulsarCluster
metadata:
  name: example-pulsarcluster
spec:
  bookie:
    size: 1
    writeCacheMaxSizeMb: 32
    readAheadCacheMaxSizeMb: 32
    image:
      repository: apachepulsar/pulsar-all
      tag: 2.5.0
      pullPolicy: Always
```
These two parameters can be configurable by adding parameters to the CR configuration file，It just hasn't been implemented yet.

**Comment by michaeljmarshall** [comment]
@sky-big - I opened https://github.com/sky-big/pulsar-operator/pull/19 to show you what I'm requesting.
