### ISSUE TITLE
some questions about deploy 

### ISSUE THREAD

**Issue by kwenzh** [sky-big/pulsar-operator#24]
1、 why pulsar-broker is kind: Deployment  to apply， not a statefulset, 
Generally pulasr broker‘s hostname  will register in zookeeper， if broker is a deployMent, how to use pulsar-broker for client, when pulsar-broker restart , broker hostname will change

2、is this pulsar-operator template support pulsar:2.8.1 ?

3、 how to set zookeeper’s storageClass， because i need persistent zookeeper datas， i only saw  bookie has storageclass in crds

**Comment by sky-big** [comment]
1. This is the Deployment defined by the older version of Pulsar Chart，It will be consistent with the latest version of Pulsar Chart later；
2. 2.8.1 is not currently supported, but will be later；
3. It will be consistent with the latest version of Pulsar Chart later；

**Comment by kwenzh** [comment]
> 1. This is the Deployment defined by the older version of Pulsar Chart，It will be consistent with the latest version of Pulsar Chart later；
> 2. 2.8.1 is not currently supported, but will be later；
> 3. It will be consistent with the latest version of Pulsar Chart later；

fine, thanks and i looking forward to using
